name: hello git action
on:
  workflow_dispatch

job:
  hello-git-action:
  runs_on: [self-hosted, git-action-runner]
  steps:
   - name: checkout
     uses: actions/checkout@v3
   - name: setup python
     uses: actions/setup-python@v4
        with:
          python-version: 3.10
   - name: run app 
     run: python app/app.py