name: hello git action

on:
  workflow_dispatch:

jobs:
  hello-git-action:
    runs-on: [self-hosted, git-action-runner]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'

      - name: Run app
        run: python app/app.py
