name: hello git action

on:
  workflow_dispatch:

jobs:
  hello-git-action:
    runs-on: [self-hosted, git-action-runner]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      

   
      - name: Run app
        run: python app/app.py
