name: docker-image-build-push

on:
    workflow_dispatch:

jobs: 
    image-build-and-push:
        runs-on: [self-hosted, git-action-runner]
        steps:
            - name: checkout
              uses: actions/checkout@v3 
            - name: login-to-harbor
              run: echo "${{ secrets.HARBOR_PASSWORD }}" | sudo docker login localhost:8080 -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

            - name: Build Docker image
              run: |
                    dsudo ocker build -t localhost:8080/test-images/hello-python:${{ github.sha }} .
            - name: docker-image-push
              run: |
                   sudo docker push localhost:8080/test-images/hello-python:${{ github.sha }}
            - name: Mattermost notification
              if: always()
              run: |
                STATUS="${{ job.status }}"
                curl -X POST -H 'Content-Type: application/json' \
                    -d '{"text": "Docker CI status: '$STATUS' for commit `${{ github.sha }}`."}' \
                    ${{ secrets.MATTERMOST_WEBHOOK }}
